name: listify
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  overflow_view: ^0.4.0  #  Latest available version on pub.dev
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  flutter_riverpod: ^2.6.1
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1
  firebase_analytics: ^11.4.6
  cloud_firestore: ^5.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: InknutAntiqua
      fonts:
        - asset: assets/fonts/InknutAntiqua-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

# Temporary fix for Flutter 3.22+ compatibility
dependency_overrides:
  value_layout_builder: ^0.5.0
